"use strict";

var found=false;
var test=true;
var fire=true;
var lastAngle=5360;
var pos={x:0,y:0};
var father=0;
var back=false;
var incr=10;
var incr2=true;
var Robot=function(a){
	father=a.id;
	a.clone();
	a.turn(180);
};
Robot.prototype.onIdle=function(a){
	var b=a.robot;
	if(found==true)if(!incr2)b.back(1);
	else b.ahead(1);
	var c=pos.x-b.position.x;
	var d=pos.y-b.position.y;
	lastAngle=Math.round(angleToDegree(Math.acos(-c/(Math.sqrt(c*c+d*d)))));
	if(d>0)lastAngle=360-lastAngle;
	if(found){if(lastAngle!=b.cannonAbsoluteAngle){var e=1;
		if(b.cannonAbsoluteAngle<lastAngle)if(lastAngle-b.cannonAbsoluteAngle>180)e=-1;
		else e=1;
		else if(b.cannonAbsoluteAngle-lastAngle>180)e=1;
		else e=-1;
		b.rotateCannon(e);
		if(Math.abs(lastAngle-b.cannonAbsoluteAngle)<50)fatherFire(b);
	}else{fatherFire(b);
		b.rotateCannon(incr);
		incr=-incr;
		fatherFire(b);
	}}else if(b.id==father)b.rotateCannon(1);
	else b.rotateCannon(-1);
};
function fatherFire(a){a.fire(a);
}function angleToDegree(a){return a*180/Math.PI;
}function degreeToRadian(a){return a*Math.PI/180;
}Robot.prototype.onScannedRobot=function(a){var b=a.robot;
	var c=a.scannedRobot;
	if((b.parentId==c.id)||(c.parentId==b.id))return;
	fatherFire(b);
	pos=c.position;
	var d=c.position.x-b.position.x;
	var e=c.position.y-b.position.y;
	var f=Math.sqrt(d*d+e*e);
	var g=Math.acos(-d/f);
	found=true;
	if(f<=400)incr=10;
	if(f<150)incr=5;
	if(f>400)incr=15;
	b.fire();
};
function setPostionToShoot(a){}
Robot.prototype.onHitByBullet=function(a){var b;
	b=a.robot;
	var c=b.angle+a.bearing;
	b.disappear();
	var d=c;
	if(d<0)d=360+d,d=d%360;
	pos.x=500*Math.sin(degreeToRadian(d))+b.position.x;
	pos.y=-500*Math.cos(degreeToRadian(d))+b.position.y;
	found=true;
	console.log("shoot"+a.bearing+" "+(Math.abs(a.bearing)%180));
	if((Math.abs(a.bearing)<30)||((Math.abs(a.bearing)<210)&&(Math.abs(a.bearing)>150))){b.ignore("onWallCollision");
	b.ignore("onRobotCollision");
	b.ignore("onHitByBullet");
	if(Math.abs(a.bearing)>30){b.turn(-30);
		b.ahead(80);
	}else{b.turn(30);
		b.back(80);
	}b.listen("onWallCollision");
	b.listen("onRobotCollision");
	b.listen("onHitByBullet");
}else b.ahead(120);
};
Robot.prototype.onRobotCollision=function(a){var b=a.robot;
	var c=a.collidedRobot;
	if((b.parentId==c.id)||(c.parentId==b.id)){}else{found=true;
		pos=a.collidedRobot.position;
	}var d=90;
	if(b.id!=father)d=90;
	else d=-90;
	b.ignore("onWallCollision");
	b.ignore("onRobotCollision");
	b.back(100);
	b.turn(-40);
	b.ahead(200);
	b.listen("onWallCollision");
	b.listen("onRobotCollision");
};
Robot.prototype.onWallCollision=function(a){var b=a.robot;
	var c=-90;
	b.turn(a.bearing+c);
};

